yamltitle: 'Susan Blair Collected'
description: 'Operational case studies, Product Manager toolbox tips, Strategies for Success, so forth.'
theme: minima

baseurl: "/SBCollected"
url: "https://github.io"
